SGLANG_ENABLE_SPEC_V2=1 python -m sglang.launch_server \
    --model-path /inspire/hdd/global_public/public_models/Qwen/Qwen3.5-122B-A10B-FP8 \
    --port 8000 \
    --tp-size 8 \
    --mem-fraction-static 0.8 \
    --context-length 262144 \
    --reasoning-parser qwen3 \
    --speculative-algo NEXTN \
    --speculative-num-steps 3 \
    --speculative-eagle-topk 1 \
    --speculative-num-draft-tokens 4 \
    --tool-call-parser qwen3_coder \
    --mamba-scheduler-strategy extra_buffer \
    --chunked-prefill-size 8192 \
    --enable-mixed-chunk \
    --schedule-policy lpm \
    --enable-cache-report